### ISSUE TITLE
Make `dsc file.dsc -h` display a module summary table

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#102]
When typing `dsc -h` we display command interface help message. It would be helpful when typing `dsc file.dsc -h` we will be able to display to the terminal [something like this](https://stephenslab.github.io/dsc-wiki/tutorials/Intro_Syntax_I.html#Planning-a-DSC-file)

```
# MODULES
# name     inputs                outputs
# ----     ------                -------
# simulate none                  $data, $true_mean
# analyze  $data                 $est_mean
# score:   $est_mean, $true_mean $error
```

We may also move the automatically generated DSC script browser (HTML file) to only work with `dsc file.dsc -h`. Then we can use this as some "debug" step for syntax etc -- one should first execute this command to see if all material are generated and are as expected, before actually running the benchmark.

**Comment by gaow** [comment]
Implemented: 

```
[GW] dsc first_investigation.dsc -h

INFO: MODULES
+---------+------------+-------+-----------------+
|         | parameters | input |      output     |
+---------+------------+-------+-----------------+
|  normal |   mu, n    |       | data, true_mean |
|    t    |   mu, n    |       | data, true_mean |
|   mean  |            |   x   |     est_mean    |
|  median |            |   x   |     est_mean    |
|  sq_err |            |  x, y |      error      |
| abs_err |            |  x, y |      error      |
+---------+------------+-------+-----------------+

INFO: PIPELINES
1: simulate  ->  analyze  ->  score

INFO: PIPELINES EXPANDED
1: normal -> mean -> abs_err
2: normal -> mean -> sq_err
3: normal -> median -> abs_err
4: normal -> median -> sq_err
5: t -> mean -> abs_err
6: t -> mean -> sq_err
7: t -> median -> abs_err
8: t -> median -> sq_err

[GW] dsc add_winsor_method2.dsc -h

INFO: MODULES
+---------+------------+-------+-----------------+
|         | parameters | input |      output     |
+---------+------------+-------+-----------------+
|  normal |   mu, n    |       | data, true_mean |
|    t    |   mu, n    |       | data, true_mean |
|   mean  |            |   x   |     est_mean    |
|  median |            |   x   |     est_mean    |
|  sq_err |            |  x, y |      error      |
| abs_err |            |  x, y |      error      |
|  winsor |    trim    |   x   |     est_mean    |
+---------+------------+-------+-----------------+

INFO: PIPELINES
1: simulate  ->  analyze  ->  score

INFO: PIPELINES EXPANDED
1: normal -> mean -> abs_err
2: normal -> mean -> sq_err
3: normal -> median -> abs_err
4: normal -> median -> sq_err
5: normal -> winsor -> abs_err
6: normal -> winsor -> sq_err
7: t -> mean -> abs_err
8: t -> mean -> sq_err
9: t -> median -> abs_err
10: t -> median -> sq_err
11: t -> winsor -> abs_err
12: t -> winsor -> sq_err
```

@pcarbo I think this might be helpful to demonstrate in Intro II? Basically I would like to free users from having to keep those "meta" comments at the top of a DSC file. All they need to do to "preview" the DSC now is to use `-h` after the file name.

**Comment by stephens999** [comment]
this looks great!

Not urgent, but we might want to also have a "dsc status" type
command which indicates (some kind of summary of)
which pipelines are unrun, run but out of date, or up to date.

Matthew

**Comment by pcarbo** [comment]
@gaow This looks great. My only tiny suggestion is to remove the double spaces in `1: simulate  ->  analyze  ->  score`.

@stephens999 Yes I agree that would be a nice feature to have.

This is related to my feature request to add a line to the output from `dsc` the command indicating which module outputs are newly generated, and which are unchanged from a previous run. @gaow Did you add an issue for this feature request?

**Comment by gaow** [comment]
Sure I've removed the space. This feature contains information that are easy to obtain because it only involves parsing the configuration, not digging into the execution. What @stephens999 has suggested is more difficult because in execution the concept of pipeline no longer exists -- they are broken down into file targets dependencies (think about Make). That said it can still be done: we'll have to first gather information from each file involved, determine the status and map back to the pipelines, then report a pooled summary. It can be very slow to generate. But such slowness is not a big issue when actually running the benchmark because these checks happen only during the runs.

@pcarbo what you've requested was similar but happens at run time which is easier. Still we are faced with mapping files back to modules for a good summary. I'll see if there is a better way to do without much overhead.
