### ISSUE TITLE
Remove ALIAS operator List / Dict

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#106]
Previously we had syntax:

```
module: exec.R
  a: 1
  b: 2
  @ALIAS: input = list(param1=a, param2=b)
```

where `input` is a script variable for `exec.R` not `a` or `b`. And we have similar stuff for Python. But this (and more!) can also be achieved by:

```
module: R(input = list(param1 = a, param2 = b)) + exec.R
  a: 1
  b: 2
```

The only difference is that the 2nd implementation will introduce additional script variables `a` and `b` but this does not harm. @stephens999 we will remove ALIAS operator. But on a second thought I'm going to put it in "Unsupported Features" page, because I imaging it is neater when:

```
module: exec.R
   a: 1
   b: 2
   c: 3
   d: 4
   (and many more parameters here)
   @ALIAS: input = list()
```

that is, `list()` means to shove all parameters to `input`. Again, not a feature we will use often or advertise, but occasionally we might find a need.

**Comment by pcarbo** [comment]
@gaow @stephens999 That sounds fine to me.
