### ISSUE TITLE
Customize runtime environment

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#115]
Related to #114 , we can allow for options to reset `PATH`, eg: 

```
@CONF: add_env = {'PATH': /path/to/path, 'PYTHONPATH': /path/to/path}
```

and under the hood we'll reset environment `PATH=/path/to/path$PATH` just for one module instance.

**Comment by pcarbo** [comment]
@gaow Two points here:

1. I think that DSC should not get into the business of modifying the shell environment. This is out of scope of DSC.

2. We want to avoid introducing anything system-dependent within the `.dsc` file. For example, if I want to share my DSC experiment with Matthew, then my `.dsc` file should not contain instructions that will only work on my computer, and not Matthew's (consider that Matthew's python may be set up differently from mine).

**Comment by gaow** [comment]
Okey let's move configuration file related discussion or in this ticket, leave Python 2 related discussion to #114. 

If we use configuration file I would vote for module specific configurations. But then we'll have to distinguish between what `@CONF` does and what a configuration file do. I think `@CONF` we will need both. eg, `@CONF` to specify (relative) paths to folders, scripts, requested (published) R and Python libraries, that DSC needs them to run. The configuration file, on the other hand, messes with bash environment and computer specific settings of interpreter paths etc.

**Comment by pcarbo** [comment]
> But what if users do use something like source activate ... for some of their modules? 

That is out of scope of DSC.

**Comment by pcarbo** [comment]
> If we use configuration file I would vote for module specific configurations.

I'm worried this is getting too complicated, and should be left for a future version of DSC if we decide that is really needed. Also, it is going against point 2 ("avoid introducing anything system-dependent within the `.dsc` file).

**Comment by gaow** [comment]
I agree with all your concerns. I (perhaps we all do) often find myself in this exact position where a bit of an engineering will provide a general solution that works for a specific user case and many more, yet added complexity to the system overall, even in the eyes of users it did not complicate dealing with simple scenarios. That is, it is a challenge to engineer and document, otherwise it will greatly hurt user experience. 

I think we can revisit this point when someone needs it for eg LD score regression? That way we really know that someone is interested and needs a way out.

**Comment by gaow** [comment]
Use #117 for a more concrete proposal.
