### ISSUE TITLE
trailing / in dsc_query

### ISSUE THREAD

**Issue by stephens999** [stephenslab/dsc#119]
not sure if this is considered a bug, but:
this works:
dscquery(dsc.outdir = "../dsc_result",
                   targets    = c("simulate","analyze","score.error"))

but this does not (added / to dsc_result/) :
dscquery(dsc.outdir = "../dsc_result/",
                   targets    = c("simulate","analyze","score.error"))

**Comment by pcarbo** [comment]
@stephens999 Yes I would consider this a bug. I think `dscquery` needs to be more careful in handling pathnames. I will ask @jdblischak for advice on handling this since I'm sure he has to worry about similar issues in `workflowr`.

**Comment by jdblischak** [comment]
Yes, path errors like this are a constant frustration for me. If you point me to the code where `dsc.outdir` and `targets` are combined, I can offer some suggestions to try.

**Comment by gaow** [comment]
Fixed at DSC level. Please test.

**Comment by pcarbo** [comment]
@gaow `dsc-query` should not be fixing bugs inside the R code.

**Comment by pcarbo** [comment]
@jdblischak This is the offending line of code:

```
dscfile <- file.path(dsc.outdir,paste0(dsc.module.files[i],".rds"))
```

where `dsc.module.files[i]` will be a (relative) pathname provided to me (and not set in the R code).

Thanks for your help.

**Comment by gaow** [comment]
@pcarbo for the example @stephens999 gave, it already works now without having to straighten out the R codes. I intend to fix it at `dsc-query` level as much as possible even when we can fix at both places, just in case that there will be future APIs that calls the same core. The same logic holds for DSC and SoS -- whenever something is generic enough to be done in SoS we do it there. It would be nice to also fix the R interface though I do not think it is completely necessary.

**Comment by pcarbo** [comment]
@gaow I reviewed the R code more carefully. You are right—the call to `dsc-query` from R was a bug in `dsc-query`, not R.

However, later in the R code, I load the results from the RDS files, and I am not using `dsc-query` there. This is potentially a second issue; @jdblischak please let me know if the "offending line of code" above could be improved.

**Comment by jdblischak** [comment]
From looking at just that [line](https://github.com/stephenslab/dsc/blob/6ca270bd94663acc493591092c67ca0746bc1772/dscrutils/R/dscquery.R#L205), I don't see anything obviously wrong with it. If one of the strings passed to `file.path` has a trailing slash, this gets added. But R should have no problem handing file paths with extra forward slashes:

```
> (path <- file.path("Desktop/", "test.txt"))
[1] "Desktop//test.txt"
> file.create(path)
[1] TRUE
> file.exists(path)
[1] TRUE
> file.remove(path)
[1] TRUE
```

Does later code try to parse the filepaths assuming only one forward slash? Also, it would be helpful to see the error message if we still think this is a problem with the R code.

**Comment by pcarbo** [comment]
@jdblischak Thanks. That is helpful. 

@gaow Feel free to close this issue now.
