### ISSUE TITLE
Summary of modules executed ans skipped

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#124]
We may want add a line to the summary indicating which module outputs are newly generated, and which are unchanged from a previous run. The complication is that in the actual execution computational jobs no longer has the concept of modules -- they are just a string hashed "job" that has its own input, script and output. Mapping these hash back to modules is possible but will need some work.

**Comment by pcarbo** [comment]
@gaow You have one `.rds` file per module, right? Does it keep track of which files exist, and which are being generated?

**Comment by gaow** [comment]
@pcarbo for the time being it is one file per module instance, not per module, and this might change down the line when we allow for multiple output files with `Shell()`. So if we do not map it back users will see that hundreds or thousands of modules are involved and get confused. Ideally it is like each module will have a little bar from 0% to 100% indicating its completion status.

**Comment by gaow** [comment]
Under the hood in SoS, we essentially only communicate between tasks and the "master" process the pass/fail status determined by shell return code. That is the only think kept. We leave status per job written to a hashed file and the `sos status` command is used to retrieve it, and even make some summary plots (feature of SoS Notebook)! This design is adopted because it is more general to where a job is run: you can imaging it is easy when all are run on the same computer and all these info get exchanged in memory. But we also run distributed jobs to multiple nodes on cluster so in-memory communication is more difficult.

**Comment by pcarbo** [comment]
@gaow In any case, I'm not sure that's relevant---my original request was about the outputs (`.rds` files) that are generated ("module instances"), not about the modules.

**Comment by gaow** [comment]
This has been partially implemented in latest `master` of SoS and DSC -- partial meaning that we do not aggregate over modules because it seems unnecessary work for me to map the computing jobs back. Verbosity level has to be set to `-v 3` -- it is a debug feature anyways.
