### ISSUE TITLE
parenthesis issue

### ISSUE THREAD

**Issue by stephens999** [stephenslab/dsc#126]
when i add this module to the dsc-reg:
```
BayesC: R(fit=BGLR::BGLR())
    X: d$X
    Y: d$Y
    $beta_est: res$ETA[[1]]$b[-1]
```

I get "ERROR: Invalid parentheses pattern in R(fit=BGLR::BGLR())"
but 
```
BayesC: R(fit=susieR::susie())
    X: d$X
    Y: d$Y
    $beta_est: res$ETA[[1]]$b[-1]
```
works (well, it crashes later, but no problem with parentheses.).

**Comment by stephens999** [comment]
it seems to be something with the ALLCAPS ...
bglr instead of BGLR does not give paranthesis problem.

```
BayesC: R(fit=BGLR::bglr())
    X: d$X
    Y: d$Y
    $beta_est: res$ETA[[1]]$b[-1]
```

**Comment by gaow** [comment]
Ahh this is in fact because I failed to handle nested `R(...R())` ... that is, if you have a call `R(susieR::susieR())` it would still fail. Sorry let me work harder on that regular expression.

**Comment by stephens999** [comment]
ha!

**Comment by gaow** [comment]
Should be fixed now -- please reopen otherwise. Moving on to next issue.
