### ISSUE TITLE
Use DSC replicate number directly as seed for RNG

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#136]
In the current implementation, the default seed for RNG is `DSC_REPLICATE_ID + SCRIPT_ID` where `SCRIPT_ID` is the current `md5sum` hash of the script file, converted to long-int. But I'm a bit bothered by the fact that each time I change the script, the results change, because the seed changes ... I think we should just use `DSC_REPLICATE_ID` as the default. If users need fancier behavior they should just set their own seeds.

**Comment by pcarbo** [comment]
@gaow I'm okay with that.

**Comment by gaow** [comment]
Great @pcarbo . Changed the behavior.

**Comment by gaow** [comment]
Reopen this issue due to @stephens999 's concern.

> using the same seed before every module just seems slightly dangerous

I'm not sure if I can immediately see the danger. My case is that each time I change my module script slightly, even cosmetic change, I end up having different result because seeds are different. That case I find that DSC default seed is no good and I will have to reset seed anyways; in other words I was saying it is not a **convenient** default to include script hash in seed. 

But I see your argument is that we prefer **safety** over convenience. I would totally agree, if you could point to me a convincing example ...

**Comment by gaow** [comment]
Maybe it is obvious, but I still like to point out that the `--touch` option to neutralize cosmetic changes will not really work for this case because as soon as `--touch` is dropped a rerun will be triggered by seed difference.

**Comment by stephens999** [comment]
ok, let's go with default of same seed on the convenience view.
and let's wait til a problem arises, in which case we can implement an
option to do the hash version.
