### ISSUE TITLE
Rename `raw` keyword `delayed`

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#139]
With #138 fixed, the operator `raw` now has 2 roles:

1. Input contents that will otherwise create a conflict in DSC interface.
2. Input a parameter whose value depends on another one. For example:

```
n: 3
m: raw(n * 2)
```

will make sure that `m` is evaluated after other parameters that do not have `raw` in them.

So I think a more appropriate name for `raw` is perhaps `delayed`? Any other suggestions?

**Comment by pcarbo** [comment]
@gaow My understanding from your description above is that 

```yaml
n: 3
m: n * 2
```

is *exactly equivalent* to

```yaml
n: raw(3)
m: raw(n * 2)
```

In other words, when no keyword is provided, implicitly you are adding `raw`. Am I wrong?

**Comment by gaow** [comment]
@pcarbo you are correct, except that currently additionally when we see `raw` explicitly we'll assume it is evaluated after other non-raw parameters are evaluated. So they'll get moved to the end of evaluation sequence. I think you've made this point in [this tutorial](https://stephenslab.github.io/dsc-wiki/tutorials/Intro_Syntax_II.html):

> Module parameters are evaluated before the module script (except when raw is used). 

I actually wanted change it to `delayed` when I was reviewing this part of the wiki yesterday. But again, I'm also okay to get rid of this explicit "feature" -- then we'll have to make an implicit assumption on the order of parameters.

**Comment by pcarbo** [comment]
> Explicitly we'll assume it is evaluated after other non-raw parameters are evaluated.

@gaow That sounds good to me.

So perhaps my interpretation in the above example is incorrect? That is,

```yaml
n: 3
m: n * 2
```

is equivalent to

```yaml
n: 3
m: raw(n * 2) 
```
because the first line is interpreted as an integer (and stored as one), whereas the second is evaluated as an R expression together with the module script? If this is correct, does this also mean that 

```yaml
m: n * 2 
n: 3
```

is valid because `m <= n * 2` will be evaluated *after* assigning the value to `n`?

> But again, I'm also okay to get rid of this explicit "feature" -- then we'll have to make an implicit assumption on the order of parameters.

For now I think that is the better approach.

**Comment by stephens999** [comment]
I would like to get rid of this "feature" and evaluate in order that they
appear in dsc file.
so
m: n * 2
n: 3

would likely produce an error but
n: 3
m: n *2
would be ok.



On Mon, May 14, 2018 at 10:41 AM, Peter Carbonetto <notifications@github.com

**Comment by gaow** [comment]
Okay, then let's get rid of that, and make parameters rely on the order of specification when unquoted strings are used ("as is" script codes). I'll now remove the obsolete text in the documentation.
