### ISSUE TITLE
Conflicting expectations with homebrew for python executable

### ISSUE THREAD

**Issue by ivirshup** [stephenslab/dsc#140]
I'm running into some trouble calling `Python` with dsc installed with `pip3`.

Here's a little example of what's happening:

```yaml
# simple.dsc
foo: Python(import sys; print(sys.version); x = y)
  y: 1
  $x: x

DSC:
  define:
    first: foo
  run: first
  output: simple
```

Running:

```bash
$ dsc simple.dsc
INFO: DSC script exported to simple.html
INFO: Constructing DSC from simple.dsc ...
INFO: Building execution graph & running DSC ...
DSC:   0%|                                                                                                      | 0/2 [00:00<?, ?it/s]ERROR: Command 'python .sos/foo_0_0_f361fe52.py' returned non-zero exit status 1.
DSC:  50%|███████████████████████████████████████████████                                               | 1/2 [00:00<00:00,  1.84it/s]
ERROR: [c35a8e94-9b2e-44ca-b04a-000e255ebc60]: [foo_0]: 
Failed to execute python .sos/foo_0_0_f361fe52.py
exitcode=1, workdir={editted: unwieldy path name}/test_python, err=simple/foo/foo_1.stderr
---------------------------------------------------------------------------
[DSC]: 1 pending step: DSC_0
WARNING: Files in green in the error prompt above contains codes and error info to help debug.
Scripts upstream of the error can be found in simple.scripts.html.
INFO: Elapsed time 2.882 seconds.

$ cat simple/foo/foo_1.stderr
Traceback (most recent call last):
  File "/var/folders/bd/43q20k0n6z15tdfzxvd22r7c0000gn/T/tmpyrt9ig9o.py", line 4, in <module>
    from dsc.dsc_io import load_dsc as __load_dsc__
ImportError: No module named dsc.dsc_io
```

My guess is that `dsc` is expecting `python` to point to `python3`, while [the default for the homebrew package manager](https://docs.brew.sh/Homebrew-and-Python) is to have `python` point to `python2`.

I've been able to get this workflow to run using a conda environment where `python` does point to `python3`, but haven't been able to get it working by aliasing `python` to `python3`.

Thanks!

**Comment by pcarbo** [comment]
@ivirshup Thank you for sharing. I believe this is already a known issue (see #117), but I think it is useful to collect addition evidence for this problem. Maybe one workaround here would be to define an alias, e.g., `alias python=python3`. Can you try this to see if it works for you?

**Comment by ivirshup** [comment]
Thanks for the quick reply!

I’ve tried setting that in my ‘.zshrc’, but I get the same problem with and without it. Is the new python instance being launched from a shell?

**Comment by pcarbo** [comment]
Try tunning the alias command directly in your current shell session (the same session where you call dsc).

**Comment by ivirshup** [comment]
```bash
$ alias python='python3'
$ which python                   
python: aliased to python3
$ dsc ./simple.dsc
INFO: DSC script exported to simple.html
INFO: Constructing DSC from ./simple.dsc ...
INFO: Building execution graph & running DSC ...
DSC:   0%|                                                                                                      | 0/2 [00:00<?, ?it/s]
ERROR: Command 'python .sos/foo_0_0_6a253f10.py' returned non-zero exit status 1.
exitcode=1, workdir=/Users/isaac/Documents/GradSchool/Project/MethodTesting/SensitivityAnalysis/DSC_testing/test_python, err=simple/foo/foo_1.stderr
...
$ cat simple/foo/foo_1.stderr
Traceback (most recent call last):
  File "/var/folders/bd/43q20k0n6z15tdfzxvd22r7c0000gn/T/tmpq8hx1_nk.py", line 4, in <module>
    from dsc.dsc_io import load_dsc as __load_dsc__
ImportError: No module named dsc.dsc_io
```

**Comment by ivirshup** [comment]
Just ran that. Did get an error on my first try:

```bash
$ ./setup.sos                                                                                         master 
INFO: Executing default_0: 
INFO: input:   []
Processing /Users/isaac/github/dsc
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bd/43q20k0n6z15tdfzxvd22r7c0000gn/T/pip-req-build-jOS3yJ/setup.py", line 38
        download_url= f'https://pypi.python.org/pypi/dsc/{__version__}#downloads',
                                                                                ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bd/43q20k0n6z15tdfzxvd22r7c0000gn/T/pip-req-build-jOS3yJ/
ERROR: Command '/bin/sh .sos/default_0_0_62597c8f.sh' returned non-zero exit status 1.
ERROR: [default_0]: 
Failed to execute /bin/sh .sos/default_0_0_62597c8f.sh
exitcode=1, workdir=/Users/isaac/github/dsc
---------------------------------------------------------------------------
```

But I got it to install with:

```bash
$ ./setup.sos --py=3
```

But after that I can get everything to install, and the test case runs without error. I'm running a longer pipeline now, but everything seems to be working fine. Thanks for the help!

**Comment by gaow** [comment]
Good to know! @ivirshup thanks for your feedback.

**Comment by pcarbo** [comment]
@gaow What was the problem exactly? SoS was using python 2.x sometimes?

**Comment by gaow** [comment]
@pcarbo no, it is because the `pip` command inside that script sometimes may use `python2` by default -- that is why we have that option `--py 3` to cope with it, and that is exactly what @ivirshup has done :)

**Comment by gaow** [comment]
I think this issue will impact anyone running Python modules with `homebrew` installed Python, a major issue of sorts. So I released version 0.2.8.4 specifically for this fix.

@ivirshup please use 

```
pip install -U --upgrade-strategy only-if-needed dsc
```

to bump your version. Thanks!

**Comment by pcarbo** [comment]
@gaow How did you resolve the issue?

**Comment by gaow** [comment]
Oh sorry @pcarbo I did not get your question earlier -- I thought you were wondering about `./setup.sos` using `python2`. The resolution of this issue is pretty dumb: because as discussed #117 we currently cannot directly interact with `python2` codes unless it is treated as an executable (and produce `file()` object results not our internal `rds` or `pkl` type of data), it would make sense to simply change the default Python interpreter inside DSC code from `python` to `python3`. This can be problematic when, maybe in a future day when `python2` is completely eliminated people will call `python3` as `python` and stop creating `python3` alias. But I do not think it is going to happen any time soon.

**Comment by pcarbo** [comment]
Thanks for the explanation @gaow.
