### ISSUE TITLE
Slow task signature check and large task `~/.sos` folder

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#144]
Also reported by @jean997 for a cluster specific feature. After doing lots of simulations on the cluster the external task signature managed by `sos task` accumulates to the point that it appears to be hanging when submitting new tasks. 

As discussed on slack, ways to resolve the issue is:

1. Automatically clean up old tasks (but how often? after every run is overkill)
2. Use time stamps instead just like snakemake (but will have problems of skewed time stamp -- time stamps is not reliable across machines)

So compromised alternatives are:

1. Clean up tasks at intervals of days.
2. Use time stamps for failed and completed tasks only. 

I think this should solve most of the problem though there are still room to optimize. Will apply these changes later and see what happens. If it is still to conservative and performance still is an issue, we can certainly explore more aggressive options.

**Comment by pcarbo** [comment]
@gaow Do we know why it is hanging? Are there many small files?

**Comment by gaow** [comment]
@pcarbo Yes we should have pretty good idea of what is going on. Many small files is part of the issue, and looking into many small files is another part of the issue. Now we will try to resolve the 2nd issue, and part of the 1st. The many small file issue (eg many files under `.sos`) has not been a big problem so far, but a better strategy than simply cleaning them up is to consolidate into some non SQL based high performance database. This is something we always wanted to do on SoS's end but never got to do it (unless driven by the need in DSC here down the line).

**Comment by pcarbo** [comment]
@gaow Perhaps you can look at Jean's account to get a better idea of what is going on? If it is due to many small files, it would be useful to know how many files and how large they are.

**Comment by gaow** [comment]
@pcarbo yes actually I wanted to do that ... but she was actively working and I didn't want to disrupt her, so we took the simple approach of deleting them all and get her a fresh start (possibly accompanied by `--touch` to avoid rerun). But it should not be too hard for me to test out the discussed fix -- I just have to run my stuff on RCC to find it out. I believe she was doing maybe a month of DSC there so I should soon reach at that point.

**Comment by gaow** [comment]
Okay the proposed solution are now ready. It should help in principle, yet I'll need to test it myself for a while. Close it for now unless the fix turns out to be ineffective later.
