### ISSUE TITLE
Ignore NA when extracting vector values

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#147]
This is related to a side effect of adjustments discussed in #145. Basically when we do not handle `NA` "smartly" then in a column like:

```
cause/simulate_8_cause_1
cause/simulate_9_cause_1
NA
NA
```
where first half is file names 2nd half is `NA`, it violates the [rules to extract vectors](https://github.com/stephenslab/dsc/blob/d1056b8fd0ae06e8f20a38142c060afa314a1dc3/dscrutils/R/dscquery.R#L243) and vectors will be left unprocessed. 

@pcarbo this is something we should fix right?

**Comment by gaow** [comment]
@pcarbo we also need the length of vectors be the same for every row:

```r
> length(NA)
[1] 1
```

**Comment by pcarbo** [comment]
@gaow But `length("cause/simulate_8_cause_1")` is also 1. Or am I missing something?

**Comment by gaow** [comment]
` cause/simulate_8_cause_1` is a file name previx so we are talking about `length(readRDS("cause/simulate_8_cause_1.rds")$param)` is greater than 1. 

I think in [these checks]() we should just skip the ones whose `value[[i]]` is `NA` . Is that reasonable?

**Comment by pcarbo** [comment]
@gaow You are right, although the NA's would have to be converted into vectors of NA's so that the extraction works correctly. I have made a note to tackle this.

**Comment by pcarbo** [comment]
@gaow Do we have an example (ideally no more complex than the `one_sample_location` example) I can use to test handling of NA's?

**Comment by gaow** [comment]
Here is Jean's example:

```
simulate: R()
  $data: 1

cause: R()
  data: $data
  z_32: 1
  z_10: 2
  gamma_ci: 3
  $res: 1:10

mr: R()
  data: $data
  $res: 1:10

gsmr(mr): R()

sim_params: R()
  data: $data
  $params_store: 1:10

DSC:
    define:
        analysis: mr, gsmr
    run: simulate*cause, simulate*analysis, simulate*sim_params
    replicate: 2
    output: results1
    exec_path: R
```

and the query:

```r
dscrutils::dscquery(dsc.outdir="results1", targets=c("sim_params.params_store", "cause.z_32", 
"cause.z_10", "cause.gamma_ci") )
```

The output is:

```
Reading DSC outputs:
 - sim_params.params_store: not extracted (filenames provided)
  DSC            sim_params.params_store cause.gamma_ci cause.z_10 cause.z_32
1   1                                 NA            3.0        2.0        1.0
2   2                                 NA            3.0        2.0        1.0
3   1 sim_params/simulate_3_sim_params_2             NA         NA         NA
4   2 sim_params/simulate_4_sim_params_2             NA         NA         NA
```

but the correct behavior is to extract a vector of length 10 for `sim_params.params_store` and make it 10 columns, eg:

```r
dscrutils::dscquery(dsc.outdir="results1", targets=c("sim_params.params_store"))
```
then without the NA artifact:
```
Loading dsc-query output from CSV file.
Reading DSC outputs:
 - sim_params.params_store: extracted vector values
  DSC sim_params.params_store.1 sim_params.params_store.2
1   1                         1                         2
2   2                         1                         2
  sim_params.params_store.3 sim_params.params_store.4 sim_params.params_store.5
1                         3                         4                         5
2                         3                         4                         5
  sim_params.params_store.6 sim_params.params_store.7 sim_params.params_store.8
1                         6                         7                         8
2                         6                         7                         8
  sim_params.params_store.9 sim_params.params_store.10
1                         9                         10
2                         9                         10
```

**Comment by gaow** [comment]
Is no longer an issue because we now save vector values in lists
