### ISSUE TITLE
Possible job misconfiguration on the cluster interface

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#154]
@jean997 In trying to reproduce the issue you reported earlier, I took the [`one_sample_location` example](https://github.com/stephenslab/dsc/tree/master/vignettes/one_sample_location) and modified my settings:

```
default:
  queue: midway2
  time_per_instance: 3m
  instances_per_job: 20
  n_cpu: 1
  mem_per_cpu: 2G

simulate:
  instances_per_job: 20
  n_cpu: 8
```

such that `mean` module uses 8 threads. Then I run:

```
./first_investigation.dsc --truncate --host midway2.yml
```
I got:

```
INFO: Running normal: 
INFO: M1_6b1e22dad1b5269b submitted to midway2 with job id 49728200
INFO: M1_efdc7a1334101a10 submitted to midway2 with job id 49728201
```

and check for status:

```
sos status M1_6b1e22dad1b5269b -v4
```

I got:

```
EXECUTION STATS:
================
M1_6b1e22dad1b5269b.sh:
=======================
#!/bin/bash
#SBATCH --time=00:03:00
#SBATCH --partition=broadwl
#
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --mem-per-cpu=2G
#SBATCH --job-name=M1_6b1e22dad1b5269b
#SBATCH --output=$HOME/.sos/tasks/M1_6b1e22dad1b5269b.out
#SBATCH --error=$HOME/.sos/tasks/M1_6b1e22dad1b5269b.err
cd /scratch/midway2/gaow/GIT/dsc/vignettes/one_sample_location
```

which says "--ntasks-per-node=8". I have not touched the specific code for `ntasks-per-node` so there should not be a need to update. (in fact please do not update to `master` because we are still making some active changes to improve pipe communications). 

Is there a way you could come up with some minimal working example? Or try to monitor it the way I did, and post your errors here, if reproducible?

**Comment by jean997** [comment]
I am still trying to reproduce it. It is very mysterious to me. One thing to note is that example has
```
 #SBATCH --ntasks-per-node={cores}
```
While I have 
```
 #SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task={cores}
```

**Comment by gaow** [comment]
This is a SBATCH syntax detail. My example was based on:

https://rcc.uchicago.edu/docs/using-midway/index.html#batch-jobs

But i'm sure you wrote it your way for a reason (some other reference you've read elsewhere). I think the point is how come the wildcard `{cores}` got expanded to an unspecified number, which I had difficulty reproducing ...

**Comment by jean997** [comment]
I deleted my `~/.sos` and local `.sos` directories and re-ran without problems. I have no idea where that 17 came from..

**Comment by gaow** [comment]
I've revamped the code for SLURM template. I think this issue is ironed out and there will be a release soon.
