### ISSUE TITLE
Automatic (or not) installation of `dscrutils`

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#160]
`dscrutils` has some essential functions to help parsing and executing DSC when R scripts are involved. Currently we automatically check and install the `master` version on github,

https://github.com/stephenslab/dsc/blob/master/src/dsc_parser.py#L106

This assumes 

1. There is internet connection
2. `devtools` has to present because we install `dscrutils` from github.

Both assumptions can be problematic. Per @jdblischak 's suggestion, we should: 

1. Check to see if dscrutils is already installed and is up to date
2. If it's not, ask the user if they would like to have dscrutils installed in their user library  (and also potentially the yaml package dependency)
3. If the user says yes, download the tarball from GitHub and install with `R CMD install` (i.e. don't bother with devtools)

For 3 we should use something along the lines of:

https://github.com/jdblischak/dsc-mouthwash/blob/677dbacd1c5cff29d78e5b65ec7b6509942de237/install.sh

Limitation of this approach is that it does not install required dependencies (`yaml`, and depending on whether or not the DSC has Python,`reticulate`). But for those dependencies we can try installing them separately via regular `install.packages` and avoid the need of `devtools`. 

In addition to 1-3 above, @jdblischak suggested making it a command option but at this point I'm a bit reluctant to do so because I want to keep the interface minimal.

**Comment by jdblischak** [comment]
Another option to consider would be to replace devtools with remotes.

https://cran.r-project.org/package=remotes

> remotes: R Package Installation from Remote Repositories, Including 'GitHub'
>
> Download and install R packages stored in 'GitHub', 'BitBucket', or plain 'subversion' or 'git' repositories. This package is a lightweight replacement of the 'install_*' functions in 'devtools'. Indeed most of the code was copied over from 'devtools'.

**Comment by pcarbo** [comment]
Automatic installation of packages is always going to be fragile (too many possible failure points to mention); I personally believe there should be an R package installation step as part of the main setup instructions, and be done with it.

**Comment by gaow** [comment]
Okay, I've disabled automatic installation of user libraries and for required libraries eg `dscrutils` I now use a command prompt to provide users a choice to let DSC handle it or to deal with it themselves. 

@jdblischak `devtools` has been replaced by `remotes` as suggested, and will only be installed on need basis. This change was implemented in SoS and will become available in next SoS release.

**Comment by jdblischak** [comment]
@gaow Sounds great!
