### ISSUE TITLE
Add "unknown" parameters? 

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#162]
Suppose I have a DSC file,

```
simulate: 
  n: 100
...
```

and I run it via:

```
dsc file.dsc
```

Now if I want to quickly evaluate what happens with `n: 10` (or just to test out the implementation), I would have to change the file to 
```
simulate:
  n: 10
```

save it, and run it via:

```
dsc file.dsc -o a_test_for_n
```

to write it to a different folder `a_test_for_n` for better book-keeping. It would be nice to be able to do this instead:

```
dsc file.dsc --simulate:n 100 -o a_test_for_n
```

where we accept "unknown" command arguments in the format of `module:parameter` and put in their values after. 

Any comments on this feature proposal? Any alternative interface suggestions?

**Comment by pcarbo** [comment]
@gaow There are many ways this could be accomplished within DSC; I don't think this feature is needed. For example, one could define a new module "simulate_test", and run that module instead. If it is important to keep results from all variants of a DSC, then one would need to consider implementing multiple DSCs (perhaps sharing common modules. I don't see this as a limitation of   the current DSC.

**Comment by gaow** [comment]
Okay so to make your idea concrete, you suggest for purpose of prototyping we

```
simulate: 
  n: 100
  other_params: ...

simulate_test(simulate):
  n: 10
```

and run

```
dsc file.dsc --target "simulate_test * ..." -o test_folder
```

instead? 

The only difference between being able to change `n` directly from command line is that the module name is now `simulate_test` which wouldnt work for the same query script as when using `simulate` module, but this can also be resolved along the lines of : 

```
define:
  simulate_all: simulate, simulate_test
```

and access it via `simulate_all`. Problem is that all these will make the DSC script a bit verbose; but possible benefit is that without allowing for command arguments, a benchmark file is self-contained.

**Comment by pcarbo** [comment]
@gaow Yes. I think you will also find that as people use DSC, they will come up with clever solutions that you hadn't anticipated. The approach should be to err on the side of a simpler tool, and not be "overly clever".

**Comment by gaow** [comment]
I implemented a restricted version of it: we'll only update variables in `DSC::global` section. For example if there is a global variable in DSC:

```
DSC:
   global:
      data_file: some_file.txt
```

in the command interface we can replace this via:

```
./susie_z.dsc ... --data_file other_file.txt
```

Let's not go further beyond this for now.
