### ISSUE TITLE
Data type issue after extracting and filling in module output values

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#166]
Here is a minimal working example:

```r
library(dscrutils)
dat <- data.frame(sim_params.params_store = c(NA,NA,5,5),
                    cause.z                 = c(0.25,0.25,NA,NA))
dsc.dir <- system.file("datafiles","misc","results1",package = "dscrutils")
out <- dscquery(dsc.dir,targets = c("sim_params.params_store","cause.z"))[-1]
```

Result:

```r
dat
```

sim_params.params_store | cause.z
-- | --
NA | 0.25
NA | 0.25
5 | NA
5 | NA

```r
out
```

sim_params.params_store | cause.z
-- | --
NA | 0.25
NA | 0.25
5 | NA
5 | NA

they look the same. But `testthat::expect_equal(dat,out)` suggest otherwise, because the first output column is not numeric:

```r
> is.numeric(out[,1])
FALSE
```

This is because the extracted column `sim_params.params_store`  was a character vector of file names and were replace element by element to the extracted numeric value, 

```r
> param = readRDS(paste0(dsc.dir, "/sim_params/simulate_2_sim_params_1.rds"))$params_store
> param
5
> is.numeric(param)
TRUE
```

but the column datatype was not changed. This also prevents subsequent operations such as filtering etc.

**Comment by pcarbo** [comment]
@gaow Please test my changes. It isn't a particularly elegant solution, but when you are revising a long  complicated function that has become almost 300 lines long, it is hard to introduce non-breaking  changes easily.

**Comment by gaow** [comment]
Thanks @pcarbo it works! Now all tests pass.
