### ISSUE TITLE
Improve performance of result database construction

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#171]
A note to myself: [this function](https://github.com/stephenslab/dsc/blob/cbb79998c207772957c5efd82e0c788d36b1c3f1/src/dsc_database.py#L106) has to be re-written for better performance. Performance for huge benchmarks might still be an issue due to upstream data structure even after I rewrite this class. ... but at least for benchmarks involving the scale > 100K module outputs we should try to get it work in a matter of seconds, not minutes. It should not be too hard to achieve.  I'm not completely satisfied with the current simple hierarchical key-value data structure we use with DSC. Let's see when we eventually reach the point that we need to drastically change the design for complex benchmarks.

**Comment by gaow** [comment]
Tried this over the past few days. Although I did manage to reduce the memory usage, the speed remains about the same. Note I was just responding to line profiling and improve codes without re-designing the data structure. Not going to push to `master` because the code is a lot less clear with hardly any speed advantage. 

I think this ticket is the most apparent performance bottleneck on DSC that can surely be improved with some efforts. Currently I rely on a simple key-value structure and a straightforward recursive search algorithm. Both the data structure and algorithm should be re-written in order to deal with larger benchmarks. 

(For others to see what I'm talking about here: the `Building DSC database ...` step can be very slow for large benchmarks eg at the scale of Yuxin's extended fine-mapping benchmark)

**Comment by gaow** [comment]
Currently at least when modules are re-executed with nothing changing, we will skip rebuilding the database.

I think the data structure should be designed such that we can layer and cache portions of the database that remains unchanged during updates (analogous to advantage of dynamic programming over naive recursion).

**Comment by stephens999** [comment]
is there any point in talking to someone in computer science about this
issue?

**Comment by gaow** [comment]
@stephens999 That would be very helpful I believe. Is there a way you could put me in touch with some computer science or engineering students or postdocs that you know of, for starters? I've got to write it up in a way that can be easily communicated to others. But it would be very helpful to run by a fellow student / postdoc as a first pass. I can use a whiteboard then.

**Comment by stephens999** [comment]
is the current database based on sql?
woudl it be enough to just ask if we can identify someone familiar with
database design for advice?

**Comment by gaow** [comment]
No it is not based on sql. But I'm open to doing it with sql -- previously I just did not see an obvious connection. Sorry I'll try to come up a version of writing. But if there is someone familiar with sql then i'd assume he's familiar in general with databases and structuring / querying information. That'd be potentially helpful already. Because it all boils down to efficiently matching unique module instances with its upstream / downstream instances (DSC syntax only matches to module definition level, not module instances level).

**Comment by stephens999** [comment]
how is this? Do you have an example of tasks that take a lot of time?

I'm wondering if there is someone (either student/postdoc or faculty)
 in your department who we could talk to to get advice on some
database-design-related issues.

Here's the short story: we are creating a workflow management system
for managing benchmarking experiments. The user specifies the elements
of the system ("modules") and the way these can be put together into
pipelines. Eg in the simplest case you would have n modules of type A,
m of type B and each pipeline would involve executing
a module from type A followed by one from type B,
creating a total of nm pipelines.
The system executes all pipelines and stores the results (including
intermediate results from each module) in files, sharing and reusing
results across pipelines
as appropriate.

We have a reasonably advanced working prototype (not quite v1.0, but nearly)
but with large projects (many modules/pipelines) some tasks can
take . quite some time and
the main developer believes performance could be substantially improved
with better data structures and design.
We feel it could be really helpful to get advice from someone
with more experience than us with database management etc.

**Comment by gaow** [comment]
> how is this? Do you have an example of tasks that take a lot of time?

Thanks @stephens999 it looks good. I do have example tasks that takes a lot time but those are too much details at this point.

There are two places that can be redesigned. I'm going to start from the one that takes more time (and fortunately is the easier one to describe) and write a document tonight on some details to share here.

**Comment by gaow** [comment]
@stephens999 @pcarbo here is a slightly more detailed version for what I need for starters:

[issue_171.pdf](https://github.com/stephenslab/dsc/files/3092224/issue_171.pdf)

(also posting the markdown file that generated this PDF for book keeping)

[issue_171.md.txt](https://github.com/stephenslab/dsc/files/3092227/issue_171.md.txt)

Although solving this will only solve half of the entire problem. The other half is harder to describe but I think it is possible that new technique I learned after solving this part can shed lights on the other part and I might be able to solve it myself then.

**Comment by gaow** [comment]
Release 0.3.8 has made some improvements over this issue. But this "improvement" came at the cost of slower performance in other parts of the code and possibly slightly in `dsc-query`. So although overall the code should be a lot faster for the scale of problems the current DSC users are working on, fundamentally it makes it worse to handle real large scale benchmark. I was willing to make this balanced choice though, and implemented it, because 1) at least we should not hear any complaints from current users at the scale of their work, and 2) bigger benchmark problem will be resolved or improved if someone can help me redesign the data structure and related implementation as I outlined in previous posts on this ticket.

**Comment by pcarbo** [comment]
@gaow When you say this:

"Currently my implementation are slow when there are lots of pipelines each containing many module instances."

Can you identify which step is the bottleneck? Are you saying that identifying the modules that have changed is a slow process?

**Comment by pcarbo** [comment]
@gaow I think it would help to sit down us to and look very carefully at this process on its own, identify the steps that require the most attention, and develop a better solution. I believe that we should be able to come up with a better solution---or determine that no better solution exists!---by thinking back to some basic ideas from data structures and algorithm design (i.e., [Cormen et al](https://mitpress.mit.edu/books/introduction-algorithms-third-edition)). I think we should look carefully at this together before we reach out to an outside party.

**Comment by gaow** [comment]
> Can you identify which step is the bottleneck? 

Yes I've profiled it.

> Are you saying that identifying the modules that have changed is a slow process?

Currently I'm not even tracking and changing only what's changed. Any small change will trigger rerunning the entire process.

**Comment by gaow** [comment]
@pcarbo Step 2 in my write up is the one that takes more time and is possibly the one we can fix on our own. Being able to track changes is bit harder but there might be standard options out there that's why maybe some other students can easily help and point it out.

**Comment by gaow** [comment]
A quick update: after clarifying the problem to @stephens999 his suggestion is we do not solve it at all, but live with a less human friendly conventions of naming things. @pcarbo I'll loop you in on this offline.

**Comment by gaow** [comment]
As discussed with others offline, we may want to do 2 things: 1) give up the nice 1-to-1 mapping of file names and use some HASH directly as is. 2) still give `sqlite` a go as the storage method and see how bad it is in practice with concurrency processes lock. The lock issue was bad based on my past experience with building sqlite-based genomic annotation databases but those databases have size of >50GB with many fields. Maybe a smaller application makes it less problematic. 

The issue with using HASH as is in 1) is that it will potentially result in arbitrarily long file names. Linux has a maximum filename length limit of 225 chars. Perhaps we've still got to use some mapping but without recycling the obsolete file names.

**Comment by pcarbo** [comment]
> The issue with using HASH as is in 1) is that it will potentially result in arbitrarily long file names. 

@gaow I thought we agreed on a solution for this. Can you please briefly summarize the proposed solution?

**Comment by gaow** [comment]
> I thought we agreed on a solution for this. Can you please briefly summarize the proposed solution?

My last sentence " Perhaps we've still got to use some mapping but without recycling the obsolete file names." is our agreed solution. But did not give details because I think we can do better than the "36 alphanumeric" theme. Will give it a stab first and report back.

**Comment by pcarbo** [comment]
Sounds good. Thanks for the summary.
