### ISSUE TITLE
Add an option to extract complex data types in `dscquery`

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#174]
As discussed with @jdblischak we would like to add to the interface of `dscquery` something like the following:

```r
dscquery(..., atomic_only = TRUE)
```

with default set to TRUE for the current behavior of the function. When `atomic_only = FALSE` we will extract and save the extracted object as nested list. We will prompt users that the return now is a nested list, and that users can use `tibble` or `purrr` (a tool @jdblischak mentioned that has some efficent methods to operate on lists) to process the results.

@pcarbo this should address your concern over some slack discussion you and @jdblischak had before? Anything to add?

**Comment by pcarbo** [comment]
@gaow When `atomic_only = TRUE`, is a data frame returned?

**Comment by gaow** [comment]
>  When atomic_only = TRUE, is a data frame returned?

yes this not only keeps backwards compatibility but also would be convenient for people who does not have clues of how nested list should be handled (I bet it is not clear to everyone that nested list can be trivially turned into data frame so we better do that for the simpler case)

**Comment by pcarbo** [comment]
@gaow That sounds good to me. I think this is best tackled simultaneously with Issue #168.

**Comment by gaow** [comment]
@pcarbo I've implemented a draft of `atomic_only` option. But when return is nested list we'll no longer be able to filter on the  results. A message will be displayed when it happens.

Would you please test and improve the documentation? In particular, some prompts that directs users to `tibble`, and possibly examples for it? There is no rush. But I'll do #168 after this one is resolved. Thanks a lot!
