### ISSUE TITLE
Behavior of `--ignore-errors`

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#191]
when `--ignore-errors` is on, it has to be used with `--touch` to avoid rerunning everything. But now I'm inclined to disable this feature because users should be responsibe to handle their errors. The most sloppy way is to use `try-catch` that most programming languages should have. I think I'll remove this feature from command interface and provide a wiki page on how to do such `try-catch` for Python and R. 

What might still warrant such an option is that for the module that fail they will impact all downstream modules and cause all of them to fail. So a single try-catch is not enough. In fact we never know how many try-catch we'll need! But this is again related to #190 so the ultimate decision will depend on if we decide to fail fast, and at which level we fail (module instance or modules, for example). 

@pcarbo am just opening tickets to document our discussions. I think I'll figure them out so no need for immediate input.

**Comment by pcarbo** [comment]
I agree that this is a feature we should remove for now.
