### ISSUE TITLE
Allow for local queues for modules

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#193]
This is to address to the issue when all computations in a module combined are still very trivial. In this case we should have them run in parallel on a compute node. We in fact have the mechanism in place, but we need examples and a recommended template for others to use.

**Comment by gaow** [comment]
@pcarbo I have updated [this page](https://stephenslab.github.io/dsc-wiki/advanced_course/Remote_Computations.html) the template to show how to allow for running on local compute node without submitting to PBS. You can look for the string `midway2.local`. You'll need to update DSC to try it out. 

Also I noticed the wiki page now links to a different template in `linear-reg` repo. And the link is broken. Do you think we should focus on improving and deciding a version of [this template](https://github.com/stephenslab/dsc/blob/master/vignettes/one_sample_location/midway.yml) and make it the official recommendation? We can talk in person about it. I think it is best we make one single recommendation consistent with what we use on that wiki page.

**Comment by pcarbo** [comment]
> I have updated this page the template to show how to allow for running on local compute node without submitting to PBS.

Normally I wouldn't use the `.yml` file at all for this; how is this different from running on a local computer?

> Also I noticed the wiki page now links to a different template in linear-reg repo.

Do you mean "dsc-linreg"? I wouldn't link to anything there. 

> I think it is best we make one single recommendation consistent with what we use on that wiki page.

Sure, let's talk about this in person on Monday.

**Comment by gaow** [comment]
> Normally I wouldn't use the .yml file at all for this

Because you asked for a mixture of configures to specify some modules to submit and some to run locally, then you'll need a syntax to distinguish them. That's what I did and documented.

> I wouldn't link to anything there.

Okay somehow it's there. Maybe its me. In any case I changed it to using the one we have in vignette.

**Comment by pcarbo** [comment]
> Because you asked for a mixture of configures to specify some modules to submit and some to run locally, then you'll need a syntax to distinguish them.

I don't think I asked for this. Maybe someone else did?

**Comment by gaow** [comment]
Oh this solves the problem when all instances in a module combined are still short-lived. It is an important feature for friendliness to RCC-like systems.
