### ISSUE TITLE
Print more complete error messages before DSC terminates

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#200]
The following `WARNING` can be improved:

```
WARNING: Substep varbvs (id=1eaca6835e85814a, index=1) returns an error. Terminating step after completing 23 submitted substeps.
```

The message should also tell us where to check the error file and / or how to reproduce it. The only possible challenge is whether we have written to disk the problematic script in question at that point (and if not we need to write it).

**Comment by pcarbo** [comment]
@gaow An alternative, if it is simpler, is to add to the message instructions on how to tell DSC to stop when an error is encountered in order to quickly obtain the error file.

**Comment by gaow** [comment]
We will revisit the `--keep-going` behavior that will also resolve this issue. I think we've had enough discussion on slack what should be done in response to errors so I'll just implement it, document and make a new DSC release.
