### ISSUE TITLE
ERROR: cannot import name 'script_to_html' from 'sos.converter' (/afs/umich.edu/user/z/a/zaczhang/anaconda3/lib/python3.7/site-packages/sos/converter.py)

### ISSUE THREAD

**Issue by ZacZZZ** [stephenslab/dsc#210]
Dear Stephenslab,

I have set up the workflow on another server.
Now I have the following error.

ERROR: cannot import name 'script_to_html' from 'sos.converter' (/afs/umich.edu/user/z/a/zaczhang/anaconda3/lib/python3.7/site-packages/sos/converter.py)

Please let me know if you need other info.

Best,

**Comment by gaow** [comment]
@ZacZZZ in this ticket #207 I have suggested that you run `pip install dsc -U` to ensure you are on version 0.3.12 unless you use the docker image. Would you please confirm `dsc --version` that you are on the right version? 

```
$ dsc --version
0.3.12
```

**Comment by ZacZZZ** [comment]
Updating dsc resolves this problem! Sorry that I missed that piece of information. Just let you know that the version of dsc 0.3.11 works on another server. I don't have roots on both serves.

**Comment by gaow** [comment]
@ZacZZZ Thanks. The reason it worked on the other server is perhaps when you set it up you had the right dependencies particularly the right (older) version of `sos`. Changes to DSC often involves changing the upstream `sos` library. But `pip install dsc -U` should also updates its dependencies so you dont have to worry about it after update.
