### ISSUE TITLE
ERROR: '.pipelines' in reproducing numerical comparison

### ISSUE THREAD

**Issue by ZacZZZ** [stephenslab/dsc#211]
Dear Stephenslab,

Thank you for your help so far. I have been making progress toward reproducing your results.
I ran into a new error when running you numerical comparison on 

And I realized that the working directory is set to ~/GIT/github/mvarbvs/dsc at some step.

Any suggestion?

```
$ sos run analysis/20180527_PIP_Workflow.ipynb cali_pip
INFO: Running cali_pip_1:
Calling dsc-query.
Running shell command:
dsc-query susie_comparison -o /tmp/Rtmpe2SS03/file615c42a50234.csv --target "liter_data.dataset liter_data lm_less lm_less.pve lm_less.n_signal fit_dap" --force
INFO: Loading database ...
INFO: Running queries ...
ERROR: '.pipelines'
Error in run_cmd(cmd.str, ferr = ifelse(verbose, "", FALSE)) :
  dsc-query command failed (returned a non-zero exit status)
Calls: <Anonymous> -> run_cmd
Execution halted
ERROR: [cali_pip_1]: [cali_pip_1]:
Failed to execute Rscript .sos/cali_pip_1_0_5ff8b2a7.R
exitcode=1, workdir=/path/to/GIT/github/mvarbvs/dsc
---------------------------------------------------------------------------
[cali_pip]: 2 pending steps: cali_pip_2, cali_pip_3
```

**Comment by gaow** [comment]
@ZacZZZ it is still something to do with old versions of DSC ... Are you using the downloaded database I provide, or is this generated from your own runs? If it is the former case I'll see if I can fix the database manually for `susie-paper` results -- I dont want to replace it because then the docker image version will not work.

**Comment by ZacZZZ** [comment]
I updated dsc from 0.3.11 to 0.3.12 and the problem persists. 
Do you refer to my own data by own runs? I am still following the instruction you posted online.
For the dsc, you might also want to update dsc install page as conda still uses the 0.3.11 version.
When I run the docker file manually some of the versions you specified seems cannot be installed

**Comment by gaow** [comment]
@ZacZZZ Okay version 0.3.12 is fine -- it is just that for that file the new version no longer works with what was generated under a previous version. Can you zip and post here the file called `susie_comparison/susie_comparison.db`? I'll see if I can manually fix it for you and get it back to you. When I do, I'll move this ticket to `susie-paper` and pin you there.

**Comment by ZacZZZ** [comment]
@gaow [susieCompDB.zip](https://github.com/stephenslab/dsc/files/3917785/susieCompDB.zip)
Here you go.

**Comment by gaow** [comment]
@ZacZZZ see here https://github.com/stephenslab/susie-paper/issues/2
