### ISSUE TITLE
Running dsc simultaneously

### ISSUE THREAD

**Issue by ZacZZZ** [stephenslab/dsc#212]
Hi Stephens Lab,

Can we run a few dsc at the same time? It works for at least one of my servers
But when I tried to toy example and susie comparison together on another server, I received 
`"libgomp: Thread creation failed: Resource temporarily unavailable"`
 from the .stderr file of susie comparison and the following error message from the toy example.

`ERROR: [cd7e75a2-abc7-4f04-b016-c6b4c354a75e]: [fit_caviar]: [(id=a3c7562927d72c10, index=10)]: Failed to obtain lock /tmp/zaczhang/.sos/2dcb8c471c494be1.lock for input toy_comparison/liter_data/liter_data_1.rds toy_comparison/get_sumstats/liter_data_1_summarize_ld_1_lm_less_1_get_sumstats_1.rds and output toy_comparison/fit_caviar/liter_data_1_summarize_ld_1_lm_less_1_get_sumstats_1_fit_caviar_3.rds. It is likely that these files are protected by another SoS process or concurrant task that is generating the same set of files. Please manually remove the lockfile if you are certain that no other process is using the lock.`

And can I know the expected running time of them (sometimes it took less than 20 seconds but it could take up to 10 hours so I wonder if there is a queuing happening on the server)?

Please let me if I need to move these issues to the susieR Github repo.

**Comment by gaow** [comment]
> Can we run a few dsc at the same time? 

Short answer is no at least for now, and what you saw is a feature we once implemented:

https://github.com/stephenslab/dsc/issues/20
