### ISSUE TITLE
A few minor typos in wiki

### ISSUE THREAD

**Issue by lwa19** [stephenslab/dsc#216]
- Docker installation “guide” not “guild”
    - https://stephenslab.github.io/dsc-wiki/advanced_course/DSC_Docker
- Typo: 'We begin “my” considering'   
    - https://stephenslab.github.io/dsc-wiki/first_course/Intro_DSC
- Typo: ‘its can value can’
    - https://stephenslab.github.io/dsc-wiki/first_course/Intro_Syntax_I
- Module inheritance is not really explained… I found it to be pretty self-evident but I'm not sure if that was intentional. 
    - https://stephenslab.github.io/dsc-wiki/first_course/Syntax_Tips.html

**Comment by gaow** [comment]
Thanks @lwa19 all issues above have been fixed.

@pcarbo @stephens999 I have implemented a github "Action" ( details [here](https://github.com/stephenslab/dsc-wiki#automatic-deployment) ). From now on, to contribute to the wiki one can simply edit those markdown or Jupyter Notebook files and push to `master`. The wiki website will be automatically generated and updated once a push is received. 

@lwa19 in the future please feel free to make minor edits that you are sure of and push them directly to the wiki. Please open tickets for those that you think should require our input. Thanks!

**Comment by pcarbo** [comment]
@lwa19 Can you please test that this works for you by making a small edit to one of the Jupyter notebooks and another small edit to one of the Markdown files?

**Comment by pcarbo** [comment]
@gaow Do we need to grant access to @alannawong and @lwa19 if they want to make changes to the DSC Wiki?

**Comment by gaow** [comment]
@pcarbo access now granted to full Stephens Lab and you are made the (co-)admin for the repo.

**Comment by lwa19** [comment]
I just tested both the Jupyter notebook and markdown files -- they are both working!

**Comment by pcarbo** [comment]
I see two commits made a few hours ago:

```
26c87dc undid test modifications
ca71ef6 modification in syntax I and debug tips
```

Thanks @lwa19!
