### ISSUE TITLE
Add an interface to extract modules' runtime

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#219]
Requested by @banskt : we should add an interface in `dscquery` to extract the runtime of modules. It should not be hard to implement if we come up with an interface for it. @banskt are you working with `dscrutils::dscquery` or directly the Python executable? I think it is easier if the interface is for dscrutils.

**Comment by banskt** [comment]
Since my request, I found that it can be extracted as `module.DSC_TIME` using `dscrutils::dscquery`.

**Comment by gaow** [comment]
@banskt Now I remember it: I added that feature a while ago but did not document it! No wonder why the request sounds familiar ... I just added a documentation to it. Thanks!
