### ISSUE TITLE
cannot import name 'execute_workflow' from 'sos' 

### ISSUE THREAD

**Issue by jean997** [stephenslab/dsc#221]
I am getting an error `ERROR: cannot import name 'execute_workflow' from 'sos' (/home/jean/miniconda3/lib/python3.7/site-packages/sos/__init__.py)` from a new installation of dsc and sos. Any ideas? My dsc version is 0.4.3.5. My sos version is 0.19.11. My python version is 3.7.3.
Thanks!
Jean

**Comment by pcarbo** [comment]
@jean997 Is this on midway2? There could be a conflict in your environment on midway2.
Can you confirm this error by running "python3" then "import sos"?

**Comment by pcarbo** [comment]
Also try upgrading `sos`. See [here](https://github.com/stephenslab/dsc) for instructions.

**Comment by jean997** [comment]
Hi Peter -- Upgrading sos solved it. This on my laptop. Thanks!
