### ISSUE TITLE
Accessing R libraries from renv

### ISSUE THREAD

**Issue by jeliason** [stephenslab/dsc#225]
I am trying to use the R libraries from my Rstudio project, which uses `renv` as the project-local dependency manager. All of these R libraries for the project are contained in an `renv/` folder at the project root. I have tried setting this path to the folder containing the libraries in `lib_path`., e.g. my DSC block looks like this
```
DSC:
  exec_path: .
  lib_path: ../renv/library/R-4.1/x86_64-pc-linux-gnu/
  R_libs: seqgendiff
  define:
    input: inputs
    simulate: sampler
    analyze: analyzer
    score: scorer
  run: input * simulate * analyze * score
  output: sims
```
This results in the error:
```
$ dsc sims.dsc --target inputs
INFO: Load command line DSC sequence: inputs
INFO: DSC script exported to sims.html
INFO: Checking R library seqgendiff ...
ERROR: R library seqgendiff is not available.
ERROR: Required R library seqgendiff is not available or obsolete. Please install it and try again.
```
even though `seqgendiff` is installed in the project, and the library folders should be accessible via `lib_path`.

Apologies if this is a dumb question - I'm a first time user of DSC.

**Comment by gaow** [comment]
@jeliason thank you for reaching out here. `lib_path` refers to directories where you put loose scripts ... The key here is to make your `bashrc` recognize where to load your R libraries. In other words, in order for DSC to work, you need to make sure this works from a commmand terminal:

```sh
R -e --slave "library(seqendiff)"
```

I don't know right off my head how to configure it for your bash environment to make it happen. Should be some variables in `~/.bashrc` or `~/.bash_profile`, or `~/.Renviron`. eg [this post](https://stackoverflow.com/questions/16049259/rstudio-different-library-path-to-command-line-r-r-libs-user)

**Comment by pcarbo** [comment]
Typically this would be done through your `.Renviron`; the [Efficient R Programming](https://csgillespie.github.io/efficientR) book explains how this is done.

**Comment by jeliason** [comment]
Thanks for your responses. I was able to get around this issue by simply setting the `lib.loc` parameter in the `library(seqgendiff)` call to the renv `library` folder. I'll close this for now.
