### ISSUE TITLE
Improve behavior of error reporting

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#97]
Currently by default running DSC on a local computer hides stderr and stdout. We should write them to files and point users to them when there are errors. We need to also clean them up if they turn out to be empty to prevent leaving behind us a trail of trivial err and out files. 

Also we need to make the rerun prompt `Rscript <path to script>` more obvious -- even suggest in the prompt that users should open up the file and interact with it.

**Comment by pcarbo** [comment]
> Currently by default running DSC on a local computer hides stderr and stdout.

@gaow Do you mean `stderr` and `stdout` from running the individual module scripts?

**Comment by gaow** [comment]
> Do you mean stderr and stdout from running the individual module scripts?

Yes. For the default verbosity level we currently hide both of them, because otherwise the screen got flooded by mostly irrelevant info from all concurrent jobs.

**Comment by pcarbo** [comment]
@gaow For debugging, it would be great to have `stderr` and `stdout` logged for all all module instances, perhaps using the naming scheme used for the `.Rds` files, with a flag to turn off logging separately for `stdout` and `stderr`. Do you think this is possible?

**Comment by pcarbo** [comment]
@gaow Having an additional flag is less important.

**Comment by gaow** [comment]
Done. This change relies on the current SoS `master` (a new SoS release is also soon to come). Documentation "debug tips" will need an update.
