### ISSUE TITLE
Calling `dsc-query` from `dscrtuils::dscquery`

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#99]
Here is the error message:

```
test = dscrutils::dscquery("dsc_result/","score")
Running shell command:
dsc-query dsc_result/ -o /var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T//RtmpY24SDG/dsc/query.csv --target score 
sh: dsc-query: command not found
Error in dscrutils::dscquery("dsc_result/", "score") : 
  dsc-query command failed (returned a non-zero exit status)
```

But `dsc-query` works from the terminal (`bash`). My guess is that R fails to honor `bash` path in its `sh` environment.

**Comment by pcarbo** [comment]
@gaow That is a good guess but unfortunately it is incorrect.

```
> system("blah")
sh: blah: command not found
> system("echo $SHELL")
/bin/bash
```

Is this error message from your computer, or Matthew's?

It is most likely that the command is not in `$PATH`. Please run the following in bash:

```bash
which dsc-query
# I get /Users/pcarbo/anaconda3/bin/dsc-query
```

and in R:

```R
echo $PATH
```

In RStudio I believe `$PATH` is not typically imported and needs to be set in `.Renviron`.

**Comment by gaow** [comment]
Ahh right, I now recall -- `bash` would too use `sh` in its command error prompt.

> Is this error message from your computer, or Matthew's? 

It is from Matthew's. I think your diagnosis is right. But is there a way to load `~/.bash_profile` automatically in RStudio?

**Comment by pcarbo** [comment]
@gaow Was Matthew using RStudio?

**Comment by gaow** [comment]
> Was Matthew using RStudio?

Yes I think so.

**Comment by pcarbo** [comment]
I think we can close this; this is an RStudio-specific issue. I will provide a solution to Matthew on Slack.

**Comment by gaow** [comment]
And on documentation? Other people are likely to run into this, too.

**Comment by pcarbo** [comment]
@gaow Sure. It could be added to the troubleshooting section.

**Comment by gaow** [comment]
Add a line in trouble-shooting section.
